import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'
import Link from 'next/link'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="min-h-screen bg-neutral-950 text-neutral-50">
        <Header />
        {children}
      </body>
    </html>
  )
}

function Header() {
  return (
    <header className="">
      <nav className="flex flex-wrap items-center justify-between gap-4 border-b border-neutral-700 p-4 font-semibold">
        <Link href="/">
          <span className="text-2xl">ShortCuts</span>
        </Link>

        <span className="rounded-md bg-gray-700 px-3 py-1 text-lg focus-within:bg-gray-500 hover:bg-gray-500 active:bg-gray-500">
          Sign In
        </span>
      </nav>
    </header>
  )
}
